# generated by appcreator
from django.contrib import admin
from . models import (
    TrpCollection,
    TrpDocument,
    TrpPage,
    TrpTranscript
)
admin.site.register(TrpCollection)
admin.site.register(TrpDocument)
admin.site.register(TrpPage)
admin.site.register(TrpTranscript)
