# generated by appcreator
from django.conf.urls import url
from . import dal_views

app_name = 'archiv'
urlpatterns = [
    url(
        r'^trpcollection-autocomplete/$',
        dal_views.TrpCollectionAC.as_view(),
        name='trpcollection-autocomplete'
    ),
    url(
        r'^trpdocument-autocomplete/$',
        dal_views.TrpDocumentAC.as_view(),
        name='trpdocument-autocomplete'
    ),
    url(
        r'^trppage-autocomplete/$',
        dal_views.TrpPageAC.as_view(),
        name='trppage-autocomplete'
    ),
    url(
        r'^trptranscript-autocomplete/$',
        dal_views.TrpTranscriptAC.as_view(),
        name='trptranscript-autocomplete'
    ),
]
