# generated by appcreator
import django_tables2 as tables
from django_tables2.utils import A

from browsing.browsing_utils import MergeColumn
from . models import (
    TrpCollection,
    TrpDocument,
    TrpPage,
    TrpTranscript
)


class TrpCollectionTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = TrpCollection
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class TrpDocumentTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')
    col_list = tables.columns.ManyToManyColumn()

    class Meta:
        model = TrpDocument
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class TrpPageTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = TrpPage
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class TrpTranscriptTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = TrpTranscript
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}

