# Generated by Django 3.0.6 on 2020-05-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trpdocument',
            name='col_list',
            field=models.ManyToManyField(blank=True, help_text='Part of Collection(s)', related_name='rvn_trpdocument_col_list_trpcollection', to='archiv.TrpCollection', verbose_name='Part of Collection(s)'),
        ),
    ]
