# Generated by Django 3.0.6 on 2020-05-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0003_auto_20200523_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trpcollection',
            name='id',
            field=models.BigIntegerField(help_text='Collection ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trpcollection',
            name='nr_of_documents',
            field=models.BigIntegerField(blank=True, help_text='Number of Documents', null=True, verbose_name='Number of Documents'),
        ),
        migrations.AlterField(
            model_name='trpcollection',
            name='page_id',
            field=models.BigIntegerField(blank=True, help_text='Page ID', null=True, verbose_name='Page ID'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='created_from_timestamp',
            field=models.BigIntegerField(blank=True, help_text='Created (start)', null=True, verbose_name='Created (start)'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='created_to_timestamp',
            field=models.BigIntegerField(blank=True, help_text='Created (end)', null=True, verbose_name='Created (end)'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='id',
            field=models.BigIntegerField(help_text='Document ID', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_done',
            field=models.BigIntegerField(blank=True, help_text='nrOfDone', null=True, verbose_name='nrOfDone'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_final',
            field=models.BigIntegerField(blank=True, help_text='nrOfFinal', null=True, verbose_name='nrOfFinal'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_gt',
            field=models.BigIntegerField(blank=True, help_text='nrOfGT', null=True, verbose_name='nrOfGT'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_in_progress',
            field=models.BigIntegerField(blank=True, help_text='nrOfInProgress', null=True, verbose_name='nrOfInProgress'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_lines',
            field=models.BigIntegerField(blank=True, help_text='nrOfLines', null=True, verbose_name='nrOfLines'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_new',
            field=models.BigIntegerField(blank=True, help_text='nrOfNew', null=True, verbose_name='nrOfNew'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_pages',
            field=models.BigIntegerField(blank=True, help_text='Number of Pages', null=True, verbose_name='Number of Pages'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_regions',
            field=models.BigIntegerField(blank=True, help_text='nrOfRegions', null=True, verbose_name='nrOfRegions'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_transcribed_regions',
            field=models.BigIntegerField(blank=True, help_text='nrOfTranscribedRegions', null=True, verbose_name='nrOfTranscribedRegions'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_transcribed_words',
            field=models.BigIntegerField(blank=True, help_text='nrOfTranscribedWords', null=True, verbose_name='nrOfTranscribedWords'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_words',
            field=models.BigIntegerField(blank=True, help_text='nrOfWords', null=True, verbose_name='nrOfWords'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_words_in_lines',
            field=models.BigIntegerField(blank=True, help_text='nrOfWordsInLines', null=True, verbose_name='nrOfWordsInLines'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='nr_of_words_in_regions',
            field=models.BigIntegerField(blank=True, help_text='nrOfWordsInRegions', null=True, verbose_name='nrOfWordsInRegions'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='orig_doc_id',
            field=models.BigIntegerField(blank=True, help_text='origDocId', null=True, verbose_name='origDocId'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='page_id',
            field=models.BigIntegerField(blank=True, help_text='Page ID', null=True, verbose_name='Page ID'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='status',
            field=models.BigIntegerField(blank=True, help_text='Status', null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='upload_time_stamp',
            field=models.BigIntegerField(blank=True, help_text='Upload Timestamp', null=True, verbose_name='Upload Timestamp'),
        ),
        migrations.AlterField(
            model_name='trpdocument',
            name='uploader_id',
            field=models.BigIntegerField(blank=True, help_text='Uploader ID', null=True, verbose_name='Uploader (ID)'),
        ),
        migrations.AlterField(
            model_name='trppage',
            name='height',
            field=models.BigIntegerField(blank=True, help_text='height', null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='trppage',
            name='id',
            field=models.BigIntegerField(help_text='Page ID', primary_key=True, serialize=False, verbose_name='Page ID'),
        ),
        migrations.AlterField(
            model_name='trppage',
            name='image_id',
            field=models.BigIntegerField(blank=True, help_text='ID of Image', null=True, verbose_name='ID of Image'),
        ),
        migrations.AlterField(
            model_name='trppage',
            name='page_nr',
            field=models.BigIntegerField(blank=True, help_text='Page Number', null=True, verbose_name='Page Number'),
        ),
        migrations.AlterField(
            model_name='trppage',
            name='width',
            field=models.BigIntegerField(blank=True, help_text='width', null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='trptranscript',
            name='gt_id',
            field=models.BigIntegerField(blank=True, help_text='gtId', null=True, verbose_name='gtId'),
        ),
        migrations.AlterField(
            model_name='trptranscript',
            name='id',
            field=models.BigIntegerField(help_text='Transcript ID', primary_key=True, serialize=False, verbose_name='Transcript ID'),
        ),
        migrations.AlterField(
            model_name='trptranscript',
            name='nr_of_lines',
            field=models.BigIntegerField(blank=True, help_text='nrOfLines', null=True, verbose_name='nrOfLines'),
        ),
        migrations.AlterField(
            model_name='trptranscript',
            name='nr_of_regions',
            field=models.BigIntegerField(blank=True, help_text='nrOfRegions', null=True, verbose_name='nrOfRegions'),
        ),
        migrations.AlterField(
            model_name='trptranscript',
            name='nr_of_transcribed_regions',
            field=models.BigIntegerField(blank=True, help_text='nrOfTranscribedRegions', null=True, verbose_name='nrOfTranscribedRegions'),
        ),
        migrations.AlterField(
            model_name='trptranscript',
            name='nr_of_words',
            field=models.BigIntegerField(blank=True, help_text='nrOfWords', null=True, verbose_name='nrOfWords'),
        ),
        migrations.AlterField(
            model_name='trptranscript',
            name='nr_of_words_in_lines',
            field=models.BigIntegerField(blank=True, help_text='nrOfWordsInLines', null=True, verbose_name='nrOfWordsInLines'),
        ),
        migrations.AlterField(
            model_name='trptranscript',
            name='nr_of_words_in_regions',
            field=models.BigIntegerField(blank=True, help_text='nrOfWordsInRegions', null=True, verbose_name='nrOfWordsInRegions'),
        ),
        migrations.AlterField(
            model_name='trptranscript',
            name='timestamp',
            field=models.BigIntegerField(blank=True, help_text='Timestamp', null=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='trptranscript',
            name='transcriber_id',
            field=models.BigIntegerField(blank=True, help_text='Transcriber (ID)', null=True, verbose_name='Transcriber (ID)'),
        ),
    ]
