# Generated by Django 3.0.6 on 2020-05-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0004_auto_20200523_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trpdocument',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='Creation Time of the Document', null=True, verbose_name='Creation Time'),
        ),
        migrations.AlterField(
            model_name='trppage',
            name='created',
            field=models.DateTimeField(blank=True, help_text='created', null=True, verbose_name='created'),
        ),
    ]
