# Generated by Django 3.0.6 on 2020-06-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0005_auto_20200524_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='trpcollection',
            name='nr_of_pages',
            field=models.BigIntegerField(blank=True, help_text='Number of Pages', null=True, verbose_name='Number of Pages'),
        ),
    ]
