# Generated by Django 3.0.6 on 2020-06-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0006_trpcollection_nr_of_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='trpdocument',
            name='as_mets',
            field=models.TextField(blank=True, null=True, verbose_name="The document's METS file"),
        ),
        migrations.AddField(
            model_name='trpdocument',
            name='as_tei',
            field=models.TextField(blank=True, null=True, verbose_name='The document as TEI file'),
        ),
    ]
